import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'EmberHeart' / 'docs' / 'SIDE_QUESTS_DB.json'
db = json.loads(p.read_text(encoding='utf-8'))

# New 10-turn versions of SQ-11 to SQ-14
upgraded_quests = [
    {
        "id": "SQ-11",
        "title": "The Prophet of Geometrics",
        "xp_reward": 900,
        "prerequisites": "None",
        "description": "A man in the Market Square is screaming that the 'Sky is a Mosaic' and that the 'Weaver' is coming to reclaim the grout.",
        "turns": [
            {"turn": 1, "narrative": "The Prophet stands on a crate of rotten melons, his eyes rolled back so far they show only white. He is drawing perfect, glowing circles in the air with a finger that has been stripped of skin. The air smells of ozone and burnt hair.", "choice_a": "Listen to the frequency of his chant (Insight DC 13)", "consequence_a": "Success: The chant is a mathematical sequence that matches the settlement's defense perimeter. (+1 Secret)", "choice_b": "Subdue him before the crowd panics (Athletics DC 12)", "consequence_b": "Success: You tackle him, but he whispers 'The grout is dry' into your ear. (+1 Progress)", "convergence": "The Prophet has a shifting ink tattoo on his forearm that is actually moving, flowing like liquid mercury."},
            {"turn": 2, "narrative": "The tattoo is a map of the 'Grey-Spire' range, but it's actively updating. It shows a 'Void-Mass' approaching the town, represented by a black smudge that eats the ink.", "choice_a": "Duplicate the map onto parchment (Dex DC 14)", "consequence_a": "Success: You have a live tracking device for the coming storm. (+1 Intel)", "choice_b": "Question his sanity in the guardhouse", "consequence_b": "Success: He reveals he was a 'Void-Watcher' from the Old World. (+1 Lore)", "convergence": "Suddenly, the Prophet's eyes turn into black glass, reflecting a sky that is shattered into thousand-mile triangles."},
            {"turn": 3, "narrative": "The Prophet's body begins to stretch and fold in ways that violate Euclidean geometry. His limbs detach and reattach at impossible angles.", "choice_a": "Strike his geometric core (Attack AC 15)", "consequence_a": "Success: You shatter the glass-like ribs. He screams in the sound of breaking mirrors. (+100 XP)", "choice_b": "Banish the entity (Arcana DC 15)", "consequence_b": "Success: You force the entity back into the 'Between-Places'. (+1 Progress)", "convergence": "The Prophet collapses, his body returning to a brittle, husk-like state, but the air around him remains 'fractured'."},
            {"turn": 4, "narrative": "The 'fractures' in the air look like ripples in a pond made of static. Through them, you can see a version of the market where the buildings are made of bone.", "choice_a": "Reach into the fracture (Dex DC 15)", "consequence_a": "Success: You pull out a shard of 'Bone-Glass'. (+1 Gear)", "choice_b": "Seal the rift with silver-wire (Repair DC 13)", "consequence_b": "Success: The vision of the bone-city fades. (+100 XP)", "convergence": "The Prophet gasps his final breath, handing you a 'Star-Glass Prism'. 'Look through the dark,' he wheezes."},
            {"turn": 5, "narrative": "The Prism feels cold, almost freezing, in your palm. Looking through it, the world is devoid of color, replaced by glowing ley-lines.", "choice_a": "Follow a ley-line (Perc DC 12)", "consequence_a": "Success: You find a hidden cache of 'Void-Capacitors' beneath the market. (+1 Loot)", "choice_b": "Analyze the ley-line nodes (Int DC 14)", "consequence_b": "Success: You realize the town is built on a massive 'Logic-Lock'. (+1 Lore)", "convergence": "A representative from the 'Silent Order'—draped in heavy, sound-dampening velvet—arrives."},
            {"turn": 6, "narrative": "The Order representative doesn't speak; they use a sign language that leaves trails of dim light in the air. They want the Prophet's remains and the Prism.", "choice_a": "Refuse and protect the Prophet's dignity", "consequence_a": "Success: The crowd rallies behind you. (+5 Morale)", "choice_b": "Negotiate for information (Persuasion DC 14)", "consequence_b": "Success: They reveal the Prophet was their escaped 'Living Archive'. (+1 Intel)", "convergence": "The representative's velvet hood slips, revealing a face composed entirely of clockwork gears."},
            {"turn": 7, "narrative": "The clockwork face ticks with a frantic, uneven rhythm. 'The Mosaic... is incomplete,' it chirps in a voice of grinding metal.", "choice_a": "Offer a drop of 'Weaver's Ichor' to the gears", "consequence_a": "Success: The ticking stabilizes. (+1 Progress)", "choice_b": "Lash out at the machine (Str DC 13)", "consequence_b": "Success: You disrupt the Order's focus. (+1 Progress)", "convergence": "The Order retreat into the shadows, but they leave behind a 'Sanctified Data-Slug'."},
            {"turn": 8, "narrative": "The Data-Slug is a slug-like entity made of soft lead, pulsed with mana. It's trying to 'speak' to your gear, vibrating your weapons.", "choice_a": "Connect the slug to your gauntlet (Tech DC 14)", "consequence_a": "Success: Your weapon gains a 'Geometric-Edge' (+1 Damage for 2 turns).", "choice_b": "Crush the slug to extract its core", "consequence_b": "Success: You gain a 'Lead-Core' (Value: 200g). (+1 Loot)", "convergence": "The Prophet's crate begins to float, the rotten melons inside freezing into perfect, crystalline spheres."},
            {"turn": 9, "narrative": "The Market Square is now a zone of 'Static Gravity'. People are floating, their screams unheard in the vacuum-like silence.", "choice_a": "Anchor the area with a 'Gravity-Well' (Int DC 15)", "consequence_a": "Success: You restore normal physics to the ward. (+5 Morale)", "choice_b": "Ride the static to the rooftops (Dex DC 14)", "consequence_b": "Success: You escape the zone and can see the 'Mosaic' clearly from above. (+1 Lore)", "convergence": "The phenomena dissipates as the Prophet's soul finally departs."},
            {"turn": 10, "narrative": "The sun rises, its light hitting the Prism in your hand. For a second, the whole market is bathed in a golden, logical clarity.", "choice_a": "Keep the Prism", "consequence_a": "Success: You have a permanent tool for seeing through Void-illusions. (+1 Gear)", "choice_b": "Give the Prism to the Council", "consequence_b": "Success: You are hailed as a hero of the state. (+100 Reputation)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Prophet's death was transition, not ending. The geometric truth he screamed is now a matter of public record, and the Silent Order is watching you from the grout.",
        "loot_table": ["Star-Glass Prism", "Sanctified Data-Slug", "Lead-Core", "900 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Geometric madness spreads. -5 Settlement Morale and a permanent -2 to all future 'Wisdom Save' rolls in town."}
    },
    {
        "id": "SQ-12",
        "title": "The Iron-Widow's Silk",
        "xp_reward": 800,
        "prerequisites": "None",
        "description": "The 'Black-Forge' is being choked by a silver, metallic silk that's harder than steel. The Widow is hungry.",
        "turns": [
            {"turn": 1, "narrative": "The forge's furnace is a dim, cooling orange. Thick, glistening strands of 'Iron-Silk' are wrapped around the bellows, pulsing with a slow, metallic heartbeat.", "choice_a": "Test the silk's tension (Athletics DC 12)", "consequence_a": "Success: You snap a minor strand, but your hand is stained with cold mercury. (+1 Progress)", "choice_b": "Heat the silk with a blowtorch", "consequence_b": "Success: The silk resists the heat, absorbing the energy. (+1 Lore)", "convergence": "A series of clicking sounds echoes from the rafters—something large is moving up there."},
            {"turn": 2, "narrative": "An 'Iron-Widow'—a spider-construct the size of a shield, made of bolted plates—descends on a single, heavy thread. Its eyes are red-hot embers.", "choice_a": "Dodge the pounce (Dex DC 13)", "consequence_a": "Success: You roll beneath the anvil, the Widow's legs striking the floor with a heavy 'thud'. (+1 Progress)", "choice_b": "Raise your shield", "consequence_b": "Success: The Widow's fangs leave deep gashes in your wood. (+100 XP)", "convergence": "The Widow retreats to the ceiling, trailing a web that is beginning to conduct the forge's remaining heat toward its nest."},
            {"turn": 3, "narrative": "The heat is being sucked out of the room. The Widow's nest—a massive sphere of silk above the furnace—is starting to glow white-hot.", "choice_a": "Target the nest with a water-bomb (Dex DC 14)", "consequence_a": "Success: The steam explosion disrupts the silk. (+1 Progress)", "choice_b": "Cut the widow's support thread (Attack DC 14)", "consequence_b": "Success: The construct falls into the cooling furnace. (+1 Progress)", "convergence": "A swarm of 'Spiderlings'—tiny, clicking gear-bugs—pours out of the silk vents."},
            {"turn": 4, "narrative": "The Spiderlings are everywhere, trying to crawl into the gaps of your armor. They smell of hot oil and charcoal.", "choice_a": "Spin and strike (Atk DC 13)", "consequence_a": "Success: You crush scores of them. (+100 XP)", "choice_b": "Use a magnetic pulse (Tech DC 12)", "consequence_b": "Success: The tiny automatons freeze and drop. (+1 Progress)", "convergence": "The Iron-Widow rises from the furnace, its plates now glowing a dangerous bright-orange."},
            {"turn": 5, "narrative": "The Widow is superheated. Its very presence is making the metal tools on the wall begin to soften and sag.", "choice_a": "Lure it to the cooling-tank (Str DC 14)", "consequence_a": "Success: You position yourself so it charges toward the water. (+1 Progress)", "choice_b": "Stun it with a 'Chilling-Flask'", "consequence_b": "Success: The thermal shock cracks its carapace. (+1 Progress)", "convergence": "The Widow hits the water with a deafening hiss, filling the room with blinding steam."},
            {"turn": 6, "narrative": "In the white mist, you can only see the glowing red eyes of the Widow. It's moving slower, but its silk is now steaming and toxic.", "choice_a": "Filter the air (Con DC 13)", "consequence_a": "Success: You maintain your breath through the vapor. (+100 XP)", "choice_b": "Track the eyes (Perc DC 14)", "consequence_b": "Success: You anticipate its next lunge. (+1 Progress)", "convergence": "You catch the Widow's main gear-joint in a vice-like grip."},
            {"turn": 7, "narrative": "The construct is struggling, its hydraulic fluid leaking like dark blood onto the floor.", "choice_a": "Execute a finishing blow (Atk DC 15)", "consequence_a": "Success: You sever the head-piece. (+1 Progress)", "choice_b": "Dismantle it for parts (Tech DC 15)", "consequence_b": "Success: You salvage the 'Widow's Heart-Gear'. (+1 Loot)", "convergence": "The main construct goes silent, but the silk nest above is still humming."},
            {"turn": 8, "narrative": "The 'Heart' of the Widow was just one part of the web. The silk is now vibrating in a specific frequency—a distress signal.", "choice_a": "Muffle the signal with sand (Repair DC 12)", "consequence_a": "Success: The vibration stops. (+1 Progress)", "choice_b": "Trace the signal's destination (Int DC 14)", "consequence_b": "Success: It's pointing to the 'Main Cog-Works' in the High-Ward. (+1 Lore)", "convergence": "The Blacksmith enters, looking at the wreckage of his forge with a mixture of horror and awe."},
            {"turn": 9, "narrative": "The Blacksmith offers you his 'Master-Work Hammer' in exchange for the silk you've cleared.", "choice_a": "Accept the Hammer", "consequence_a": "Success: You gain a weapon that can repair as well as destroy. (+1 Gear)", "choice_b": "Exchange the silk for 'Hardened Scales'", "consequence_b": "Success: You gain material for superior armor. (+1 Gear)", "convergence": "The furnace is relit. The fire burns steady and blue."},
            {"turn": 10, "narrative": "As you leave, you see a small, silver strand trailing from your boot. The silk is persistent.", "choice_a": "Burn the strand away", "consequence_a": "Success: You are clean. (+100 XP)", "choice_b": "Keep it as a trophy", "consequence_b": "Success: It pulses when constructed objects are near. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Iron-Widow has been dismantled, and the Black-Forge is back in production. But the signal it sent suggests a 'Mother-Widow' may be waiting in the foundations.",
        "loot_table": ["Widow's Heart-Gear", "Master-Work Hammer", "800 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Forge stays cold. -5 Resources and -2 to all future 'Gear-Repair' rolls."}
    },
    {
        "id": "SQ-13",
        "title": "The Salt-Sump Siphon",
        "xp_reward": 850,
        "prerequisites": "None",
        "description": "The 'Salt-Sumps' are overflowing with a brine that is corrosive to the soul. A rogue siphon is pumping the liquid into the drinking water.",
        "turns": [
            {"turn": 1, "narrative": "The sumps are a series of deep, stone vats filled with a thick, iridescent white liquid that tastes like copper and tears. The air is so salty it makes your eyes sting and your skin itch.", "choice_a": "Identify the brine's origin (Alchemist DC 12)", "consequence_a": "Success: You realize the salt is 'Condensed Despair'. (+1 Lore)", "choice_b": "Follow the siphon pipe (Perc DC 11)", "consequence_b": "Success: You find the pipe leading into a hidden sub-basement. (+1 Progress)", "convergence": "The floor tiles here are covered in a thin, white crust of salt that crunches like bone."},
            {"turn": 2, "narrative": "A man is hunched over the main valve, his clothes white as ghosts. He's talking to the brine, whispering secrets that make the liquid bubble.", "choice_a": "Confront the Saboteur", "consequence_a": "Success: He looks at you with eyes that have been bleached white. (+1 Progress)", "choice_b": "Sneak closer (Stealth DC 13)", "consequence_b": "Success: You see he's using a 'Void-Siphon'—a device prohibited by the Council. (+1 Secret)", "convergence": "The Saboteur screams and kicks a lever, causing a high-pressure jet of brine to spray toward you."},
            {"turn": 3, "narrative": "The brine is corrosive. It's not just eating your armor; it's eating your memories. You feel a sudden, sharp pang of loss for a childhood friend whose name you can't remember.", "choice_a": "Hold on to your identity (Con Save DC 14)", "consequence_a": "Success: You maintain your sense of self through the mental rot. (+1 Progress)", "choice_b": "Dodge the spray (Dex DC 14)", "consequence_b": "Success: You avoid the worst of the liquid. (+100 XP)", "convergence": "The room is filling with brine. The Saboteur has locked the exit and is laughing hysterically."},
            {"turn": 4, "narrative": "The water is at your knees. You see the Saboteur attempting to merge with the brine, his skin turning into translucent salt-crystals.", "choice_a": "Pull him out of the vat (Str DC 15)", "consequence_a": "Success: You save him from 'The Great Dissolve'. (+1 Progress)", "choice_b": "Smash the Siphon (Atk DC 14)", "consequence_b": "Success: The mechanism shatters, and the flow stops. (+1 Progress)", "convergence": "The brine begins to drain away, but it's leaving behind a 'Salt-Phantom'—a humanoid figure made of swirling crystals."},
            {"turn": 5, "narrative": "The Salt-Phantom moves with a jerky, unnatural rhythm. It speaks with the voices of a thousand grieving mothers.", "choice_a": "Dispel the phantom (Religo DC 14)", "consequence_a": "Success: The brine-spirit evaporates into a cloud of steam. (+100 XP)", "choice_b": "Shatter its form (Atk DC 15)", "consequence_b": "Success: The phantom explodes into a thousand harmless shards. (+1 Progress)", "convergence": "The Saboteur is unconscious on the ground, his body a living map of salt-burns."},
            {"turn": 6, "narrative": "You find a journal on his belt. It contains a list of every person he intended to 'Purify' with the brine.", "choice_a": "Read the names (Int DC 13)", "consequence_a": "Success: You find several Council members on the list. (+1 Intel)", "choice_b": "Burn the journal", "consequence_b": "Success: You decide some truths are better left buried. (+1 Morale)", "convergence": "The local guards arrive, led by a Sump-Captain who looks suspicious of your presence."},
            {"turn": 7, "narrative": "The Captain demands to know if you were working with the Saboteur. He's looking at the Void-Siphon in your hand.", "choice_a": "Persuade him of your innocence (Charisma DC 14)", "consequence_a": "Success: He accepts your story and thanks you. (+1 Progress)", "choice_b": "Intimidate him into silence (Str DC 15)", "consequence_b": "Success: He backs down, but his loyalty is now zero. (+1 Progress)", "convergence": "He offers you a 'Salt-Guard's Pouch' as a bribe or a reward, depending on your tone."},
            {"turn": 8, "narrative": "The Sump is safe, but the damage to the water supply will take days to fix. The townspeople are thirsty and angry.", "choice_a": "Provide a clean water source (Survival DC 13)", "consequence_a": "Success: You find an old, forgotten well in the ruins. (+5 Morale)", "choice_b": "Organize a water-rationing plan", "consequence_b": "Success: You prevent a riot. (+5 Reputation)", "convergence": "The sun sets, the horizon turning a salt-white as the moon rises."},
            {"turn": 9, "narrative": "The Saboteur wakes up in the cell. He begs for one last drop of the brine. He says the salt is 'The Only Way to Forget'.", "choice_a": "Give him a drop (Evil Action)", "consequence_a": "Success: He smiles and dissolves into dust. (+1 Secret)", "choice_b": "Offer him fresh water", "consequence_b": "Success: He weeps and begins to repent. (+1 Morale)", "convergence": "The Siphon is dismantled, and the Salt-Sump is sealed with iron bars."},
            {"turn": 10, "narrative": "You look at your reflection in a cup of clean water. Your eyes look a little more tired, but your soul is intact.", "choice_a": "Rest at the Tavern", "consequence_a": "Success: You recover your memories. (+1 Luck)", "choice_b": "Check the walls for more siphons", "consequence_b": "Success: You find nothing, but the paranoia remains. (+1 Lore)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Salt-Sump Siphon was a localized madness, but the presence of the Void-Siphon suggests that someone is supplying these forbidden tools to the desperate.",
        "loot_table": ["Salt-Guard's Pouch", "Saboteur's Journal", "Brine-Crystal Shard", "850 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Water supply corrupted. -10 Health and -5 Morale for all residents."}
    },
    {
        "id": "SQ-14",
        "title": "The Flicker-Man's Shadow",
        "xp_reward": 950,
        "prerequisites": "None",
        "description": "A 'Flicker-Man'—a survivor who was caught in a warp-rift—has returned. He's leaving shadows that move on their own.",
        "turns": [
            {"turn": 1, "narrative": "The Flicker-Man sits in the tavern, his body semi-translucent. Every few seconds, he 'blinks' out of existence and reappears an inch to the left. His shadow, however, remains fixed to the floor, staring up at him.", "choice_a": "Communicate with the Flicker-Man (Insight DC 13)", "consequence_a": "Success: He tells you he's 'caught between frequencies'. (+1 Lore)", "choice_b": "Observe the shadow's behavior (Perc DC 14)", "consequence_b": "Success: You notice the shadow is slowly peeling itself off the floor. (+1 Progress)", "convergence": "The tavern lights begin to flicker in a rhythmic, stuttering pattern."},
            {"turn": 2, "narrative": "With every flicker of light, the shadow grows larger. It's no longer just a silhouette; it's gaining three dimensions, its surface like oily black velvet.", "choice_a": "Interpose your own shadow (Int DC 12)", "consequence_a": "Success: You confuse the entity's growth pattern. (+100 XP)", "choice_b": "Strike the shadow with a cold-iron blade", "consequence_b": "Success: The blade passes through, but the shadow recoils as if burned. (+1 Progress)", "convergence": "The Flicker-Man screams as his shadow begins to pull him into the floorboards."},
            {"turn": 3, "narrative": "The floorboards are turning into a liquid, black tarp. The Flicker-Man is chest-deep in the shadow-mire. 'Help me find my anchor!' he cries.", "choice_a": "Pull him out with a rope of light (Arcana DC 14)", "consequence_a": "Success: You haul him back to the physical plane. (+1 Progress)", "choice_b": "Dive into the shadow-mire to pull him from below (Str DC 15)", "consequence_b": "Success: You enter the 'Flip-Side' momentarily. (+1 Secret)", "convergence": "The Flicker-Man is free, but the shadow has now fully detached and is standing behind the bar."},
            {"turn": 4, "narrative": "The Shadow-Man is a perfect, featureless copy of the Flicker-Man. It reaches for a bottle of 'Glint-Wine' and drinks it; the wine simply vanishes into its chest.", "choice_a": "Reason with the Shadow-Man", "consequence_a": "Success: It speaks in a voice like a radio between stations. (+5 Lore)", "choice_b": "Attack the Shadow-Man (Atk DC 15)", "consequence_b": "Success: You slice through its chest, but it simply reforms. (+1 Progress)", "convergence": "The Flicker-Man reveals that his 'Anchor'—a copper watch—is still in the warp-rift zone."},
            {"turn": 5, "narrative": "You must travel to the 'Jagged-Fissure', a place where physics is a suggestion. The air here tastes like copper and old static.", "choice_a": "Navigate the static (Survival DC 14)", "consequence_a": "Success: You find the path through the shifting rocks. (+100 XP)", "choice_b": "Use a 'Warp-Scanner' (Tech DC 13)", "consequence_b": "Success: You locate the copper watch immediately. (+1 Progress)", "convergence": "The watch is floating in the center of a miniature vortex of violet lightning."},
            {"turn": 6, "narrative": "The vortex is trying to pull you in. Around the watch, you can see 'After-Images' of the Flicker-Man's life—his wedding, his first house, his death.", "choice_a": "Reach for the watch (Dex DC 15)", "consequence_a": "Success: You snatch the watch from the center of the storm. (+1 Progress)", "choice_b": "Disrupt the vortex with a force-wave", "consequence_b": "Success: The storm collapses, and the watch falls. (+100 XP)", "convergence": "You have the Anchor. The air in the fissure suddenly goes quiet, but your skin is tingling."},
            {"turn": 7, "narrative": "The Shadow-Man appears behind you in the fissure. It's much stronger here. It wants the watch to complete its takeover.", "choice_a": "Offer the watch to the Shadow", "consequence_a": "Success: The Shadow merges with the watch, becoming a 'Shadow-Sentinel'. (+1 Gear)", "choice_b": "Smash the watch on the rocks", "consequence_b": "Success: You destroy the link, weakening the Shadow. (+1 Progress)", "convergence": "The Shadow-Man lunges for you, his hands like knives of solidified darkness."},
            {"turn": 8, "narrative": "The fight is taking place in two dimensions at once. Every strike you land on the Shadow is echoed in your own mind as a bad memory.", "choice_a": "Maintain mental focus (Wis Save DC 14)", "consequence_a": "Success: You shrug off the psychic feedback. (+1 Progress)", "choice_b": "Unleash a 'Nova-Flash' to end the darkness", "consequence_b": "Success: The Shadow is disintegrated. (+1 Progress)", "convergence": "The Flicker-Man appears at the edge of the fissure, his body finally solid and steady."},
            {"turn": 9, "narrative": "The Flicker-Man thanks you. He looks older now, his hair turned white by the experience. He gives you his 'Warp-Cap' as a reward.", "choice_a": "Accept the Cap", "consequence_a": "Success: You gain a headpiece that allows for short-range blinks. (+1 Gear)", "choice_b": "Decline and buy him a drink at the tavern", "consequence_b": "Success: You gain a loyal informant in the Fringe. (+5 Reputation)", "convergence": "The sun begins to set, the shadows returning to their proper, two-dimensional places."},
            {"turn": 10, "narrative": "You sit on the edge of the fissure, watching the violet lightning fade. The world feels a little more solid today.", "choice_a": "Write a report for the Council", "consequence_a": "Success: They reward you with gold for the data. (+750 Gold)", "choice_b": "Rest and recover", "consequence_b": "Success: You lose the 'Flicker-Tint' from your skin. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Flicker-Man is anchored, and the Shadow-Man is gone. But the Jagged-Fissure remains open, a wound in the world that won't stop bleeding.",
        "loot_table": ["Warp-Cap", "Shadow-Sentinel Watch", "Copper Anchor", "950 Gold"],
        "risk_matrix": {"failure_threshold": 4, "penalty": "Flicker-sickness spreads. -5 Health and -2 to all Dexterity checks for a week."}
    }
]

# Update the database
for i, q in enumerate(db):
    for uq in upgraded_quests:
        if q['id'] == uq['id']:
            db[i] = uq

p.write_text(json.dumps(db, indent=4), encoding='utf-8')
print("SUCCESS: SQ-11 to SQ-14 upgraded to 10-turn Lush Standard.")
