import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'EmberHeart' / 'docs' / 'SIDE_QUESTS_DB.json'
db = json.loads(p.read_text(encoding='utf-8'))

upgraded_batch_2 = [
    {
        "id": "SQ-15",
        "title": "The Glass-Lung Sickness",
        "xp_reward": 700,
        "prerequisites": "None",
        "description": "Refugees working the 'Silica-Vents' are breathing in microscopic glass shards. Something is turning the sand into razors.",
        "turns": [
            {"turn": 1, "narrative": "The Silica-Vents are beautiful and deadly, filled with a fine, silver dust that hangs in the air like frozen fog. The workers cough into blood-stained rags, their lungs wheezing like old organs.", "choice_a": "Examine the filter systems (Repair DC 12)", "consequence_a": "Success: You find the filters have been precisely slit by a laser-like cut. (+1 Intel)", "choice_b": "Heal a suffering worker (Medic DC 13)", "consequence_b": "Success: You extract a perfect, jagged cube of glass from their throat. (+1 Lore)", "convergence": "A rhythmic 'clinking' sound comes from the main ventilation shaft, like glass chimes in a storm."},
            {"turn": 2, "narrative": "The clinking is coming from a 'Sand-Sifter'—a small, crab-like construct made of fused obsidian. It's actively grinding rocks into the lethal dust.", "choice_a": "Disable the Sifter (Tech DC 13)", "consequence_a": "Success: You snap its grinding-pincers. (+1 Progress)", "choice_b": "Trace its power source (Perc DC 14)", "consequence_b": "Success: It's being powered by an illegal 'Warp-Battery'. (+1 Secret)", "convergence": "The Sifter explodes into a cloud of glass-shrapnel that threatens to shred your cloak."},
            {"turn": 3, "narrative": "The shrapnel is everywhere. You see the dust beginning to swirl and coalesce into a 'Dust-Demon'—a vortex of grinding silica.", "choice_a": "Dampen the air with water-vials", "consequence_a": "Success: The dust becomes heavy and falls to the floor. (+1 Progress)", "choice_b": "Shield the workers with your body (Con DC 14)", "consequence_b": "Success: You take the hits, protecting the innocent. (+100 XP)", "convergence": "The Dust-Demon dissipates, but the air remains thick with the smell of scorched minerals."},
            {"turn": 4, "narrative": "You reach the 'Vent-Control' room. The screens are flickering with images of the 'Glass-Widow'—a mythical figure from the Low-Wastes.", "choice_a": "Access the core logs (Int DC 15)", "consequence_a": "Success: You learn the sabotage was ordered by a rogue faction. (+1 Lore)", "choice_b": "Lock down the ventilation (Tech DC 13)", "consequence_b": "Success: You stop the spread of the dust. (+1 Progress)", "convergence": "A hidden door opens, revealing a chamber filled with 'Lungs of Glass'—preserved human organs transformed into crystal."},
            {"turn": 5, "narrative": "The crystal lungs are pulsing with a rhythmic light. They're being used as 'Bios-Processors' for an unknown calculation.", "choice_a": "Destroy the processors (Atk DC 14)", "consequence_a": "Success: You end the horrific experiment. (+1 Progress)", "choice_b": "Extract the data-cores (Int DC 14)", "consequence_b": "Success: You gain a 'Glass-Memory Crystal'. (+1 Loot)", "convergence": "The facility begins to self-destruct, the glass walls cracking and howling."},
            {"turn": 6, "narrative": "A 'Glass-Sentinel'—a humanoid made of mirrors—steps out from the reflections. It mimics your every move exactly.", "choice_a": "Close your eyes and fight by sound (Perc DC 15)", "consequence_a": "Success: You shatter the illusion. (+1 Progress)", "choice_b": "Strike your own reflection (Str DC 14)", "consequence_b": "Success: The Sentinel cracks in sympathy with your blow. (+1 Progress)", "convergence": "The Sentinel shatters into a million pieces, revealing a path to the surface."},
            {"turn": 7, "narrative": "The exit is blocked by a wall of solidified silica. It's too thick to break with standard tools.", "choice_a": "Use a 'Thermal-Charge' (Tech DC 14)", "consequence_a": "Success: You melt a hole through the wall. (+1 Progress)", "choice_b": "Find a bypass through the vents (Dex DC 13)", "consequence_b": "Success: You crawl through the narrow, glass-lined ducts. (+100 XP)", "convergence": "You emerge into the cool night air, but your skin is glowing with a faint, silver sheen."},
            {"turn": 8, "narrative": "A medical team meets you. They're terrified of the 'Glass-Sheen'—it's the first stage of the transformation.", "choice_a": "Undergo a 'Pulse-Purge' (Con Save DC 15)", "consequence_a": "Success: You burn the silica from your pores. (+100 XP)", "choice_b": "Seek help from the Alchemists", "consequence_b": "Success: They provide a 'Silica-Dampener'. (+1 Gear)", "convergence": "The vents are quiet. The silica dust has settled."},
            {"turn": 9, "narrative": "The worker you saved offers you a 'Shard-Knife'. He says it's a family heirloom, used to cut through the hardest truths.", "choice_a": "Accept the knife", "consequence_a": "Success: You gain a weapon that ignores armor. (+1 Gear)", "choice_b": "Decline and buy him medical supplies", "consequence_b": "Success: Your reputation for kindness grows. (+5 Rep)", "convergence": "The Council declares the Silica-Vents a 'Restricted Zone'."},
            {"turn": 10, "narrative": "You look at the vents from the safety of the Ridge. They look like a field of diamonds in the moonlight—a beautiful, silent graveyard.", "choice_a": "Write a warning for the miners", "consequence_a": "Success: You save future lives. (+10 Morale)", "choice_b": "Keep a vial of the dust (Secret DC 14)", "consequence_b": "Success: You have a lethal, invisible weapon. (+1 Secret)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Glass-Lung Sickness was a test of biological processing. You stopped the experiment, but the 'Glass-Widow' knows your face.",
        "loot_table": ["Shard-Knife", "Glass-Memory Crystal", "Silica-Dampener", "700 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Outbreak spreads. -5 Health for all workers and increased cost of medical supplies."}
    },
    {
        "id": "SQ-16",
        "title": "The Wailing Pipe",
        "xp_reward": 550,
        "prerequisites": "None",
        "description": "The 'High-Steampunk' district is being plagued by a sound that drives people to madness. It's coming from the Sewer-Main-09.",
        "turns": [
            {"turn": 1, "narrative": "Sewer-Main-09 is a cavern of dripping brass and green slime. The 'Wail' is a high-pitched, metallic shriek that makes your nose bleed. It sounds like a woman screaming through a flute of rusted iron.", "choice_a": "Block the resonance (Repair DC 12)", "consequence_a": "Success: You stuff rags into the vibrating joints. (+1 Progress)", "choice_b": "Analyze the sound's pattern (Perc DC 13)", "consequence_b": "Success: It's not a random noise; it's a 'Data-Stream' in audio form. (+1 Lore)", "convergence": "A thick, black oil is oozing from the pipe joints, forming patterns on the walls."},
            {"turn": 2, "narrative": "The oil is forming words in an ancient tongue. It says: 'THE GATES ARE OPEN'. A 'Pipe-Stalker'—a lanky humanoid made of copper tubing—unfolds from the ceiling.", "choice_a": "Defend yourself (Atk DC 13)", "consequence_a": "Success: You strike the tubing, sending sparks into the dark. (+1 Progress)", "choice_b": "Disassemble the Stalker (Tech DC 14)", "consequence_b": "Success: You find its 'Voice-Box' is a stolen music box from the High-Ward. (+1 Secret)", "convergence": "The Stalker retreats deeper into the pipes, leaving a trail of the black oil."},
            {"turn": 3, "narrative": "The wailing is intensifying. You find a 'Pressure-Valve' that is vibrating so hard it's glowing a dull red. It's about to burst.", "choice_a": "Vent the pressure (Str DC 14)", "consequence_a": "Success: You release a spray of superheated steam. (+100 XP)", "choice_b": "Cool the valve with a 'Frost-Gem'", "consequence_b": "Success: You stabilize the metal. (+1 Progress)", "convergence": "The steam clears, revealing a 'Void-Larva'—a pulsing, purple grub—attached to the valve stem."},
            {"turn": 4, "narrative": "The Larva is the source of the sound. It's 'screaming' as it drinks the mana from the steam system.", "choice_a": "Extract the Larva (Dex DC 14)", "consequence_a": "Success: You capture it in a lead jar. (+1 Loot)", "choice_b": "Crush the Larva", "consequence_b": "Success: The sound stops instantly, replaced by a haunting silence. (+1 Progress)", "convergence": "The pipe walls begin to cave in—the Larva was the only thing holding the pressure back."},
            {"turn": 5, "narrative": "You're in a race against the flood. The black oil is rising, and the smell of ozone is overwhelming.", "choice_a": "Sprint for the exit (Athletics DC 13)", "consequence_a": "Success: You outrun the collapse. (+100 XP)", "choice_b": "Seal the breach with 'Forge-Glue' (Tech DC 15)", "consequence_b": "Success: You save the district from flooding. (+5 Morale)", "convergence": "You reach a safe-room, but the door is jammed from the outside."},
            {"turn": 6, "narrative": "Through the door's porthole, you see a 'Gate-Keeper'—a robot with a megaphone for a head. It's broadcasting the Wail to the upper city.", "choice_a": "Disable the broadcaster (Atk DC 14)", "consequence_a": "Success: You silence the megaphone. (+1 Progress)", "choice_b": "Reason with the machine-spirit (Arcana DC 14)", "consequence_b": "Success: You learn it was programmed to 'Warn the World'. (+1 Intel)", "convergence": "The Gate-Keeper powers down, its megaphone head drooping like a wilted flower."},
            {"turn": 7, "narrative": "The 'Wail' has been silenced, but the black oil is now glowing with a faint, violet light. It's 'Living Ink'.", "choice_a": "Collect the ink (Int DC 13)", "consequence_a": "Success: You gain a 'Vial of Living Ink'. (+1 Loot)", "choice_b": "Analyze the ink's composition", "consequence_b": "Success: It's made of 'Script-Mana'—the code of the world. (+1 Lore)", "convergence": "The Sewer-Main door opens, revealing the City Engineer, his face white with fear."},
            {"turn": 8, "narrative": "The Engineer offers you a 'Master-Key' to the sewers if you keep the 'Living Ink' a secret.", "choice_a": "Accept the Key", "consequence_a": "Success: You can now travel the city's depths with ease. (+1 Gear)", "choice_b": "Report the incident to the Council", "consequence_b": "Success: Your reputation for honesty rises. (+5 Reputation)", "convergence": "The 'Wailing Pipe' is replaced with a standard iron conduit."},
            {"turn": 9, "narrative": "As you walk home, you hear a faint echo of the wail from your own pocket. The Larva (if you took it) is still screaming.", "choice_a": "Feed the Larva a sugar-cube", "consequence_a": "Success: It purrs, a sound like a distant cello. (+1 Luck)", "choice_b": "Give it to the University", "consequence_b": "Success: They reward you with a 'Scholar's Purse'. (+1 Gear)", "convergence": "The High-Steampunk district is quiet once more."},
            {"turn": 10, "narrative": "The night air is clear. You look at the stars, and for a second, you think they're vibrating in the same frequency as the pipe.", "choice_a": "Go to sleep", "consequence_a": "Success: No nightmares tonight. (+1 Luck)", "choice_b": "Check the other sewer mains", "consequence_b": "Success: You find nothing, but you feel the 'Wail' is still out there. (+1 Lore)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Wailing Pipe was a warning. The 'Living Ink' suggests that someone is rewrite the script of the city from below.",
        "loot_table": ["Vial of Living Ink", "Sewer Master-Key", "Lead Larva Jar", "550 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "District evacuated. -2 Morale and -5 Local Resources."}
    },
    {
        "id": "SQ-17",
        "title": "The Rust-Worms' Feast",
        "xp_reward": 600,
        "prerequisites": "None",
        "description": "A swarm of 'Rust-Worms' has invaded the central granary. They don't eat grain; they eat the silos.",
        "turns": [
            {"turn": 1, "narrative": "The granary is a massive complex of corrugated iron silos. The 'Rust-Worms' are three-foot-long, segmented monstrosities with saws for mouths. They are chewing through the thick metal like it's paper.", "choice_a": "Identify the swarm's leader (Nature DC 12)", "consequence_a": "Success: You spot a 'Prime-Worm' with a golden carapace. (+1 Progress)", "choice_b": "Spray 'Rust-Resistant' coating (Tech DC 13)", "consequence_b": "Success: You slow their feast significantly. (+1 Progress)", "convergence": "A silo collapses, spilling tons of 'Spark-Grain' across the floor."},
            {"turn": 2, "narrative": "The Spark-Grain is highly flammable. The Rust-Worms' chewing is creating friction and sparks. The air is a powder-keg.", "choice_a": "Dampen the grain with foam (Dex DC 13)", "consequence_a": "Success: You prevent an explosion. (+100 XP)", "choice_b": "Lure the worms away with iron-scraps", "consequence_b": "Success: The majority of the swarm follows the 'Easy Meal'. (+1 Progress)", "convergence": "The Prime-Worm roars, a sound like a circular saw hitting a nail, and charges you."},
            {"turn": 3, "narrative": "The Prime-Worm's saw-mouth is spinning at thousands of RPM. It's aiming for your legs.", "choice_a": "Jump and strike from above (Atk DC 14)", "consequence_a": "Success: You land on its back, avoiding the saws. (+1 Progress)", "choice_b": "Parry with a heavy shield (Str DC 14)", "consequence_b": "Success: You hold your ground, but your shield is badly scarred. (+100 XP)", "convergence": "The Prime-Worm retreats into a grain-pile, its golden shell glowing with a manic energy."},
            {"turn": 4, "narrative": "You're waist-deep in the Spark-Grain. You can feel the worms moving beneath the surface like sharks.", "choice_a": "Use a 'Vibration-Pulse' (Tech DC 14)", "consequence_a": "Success: You force the worms to the surface. (+1 Progress)", "choice_b": "Listen for their movement (Perc DC 14)", "consequence_b": "Success: You anticipate the next ambush. (+100 XP)", "convergence": "A hidden vent opens, and a 'Grain-Watcher'—a robotic scarecrow—steps into the room."},
            {"turn": 5, "narrative": "The Grain-Watcher is malfunctioning, firing 'Harpoon-Bolts' at anything that moves—including you.", "choice_a": "Hack the Watcher (Tech DC 15)", "consequence_a": "Success: You turn its weapons on the worms. (+1 Progress)", "choice_b": "Dismantle the Watcher (Atk DC 14)", "consequence_b": "Success: You salvage its 'Harpoon-Launcher'. (+1 Gear)", "convergence": "The worms are being thinned out, but the Prime-Worm is now twice its original size."},
            {"turn": 6, "narrative": "The Prime-Worm has eaten the Watcher's battery. It's now trailing lightning alongside its saws.", "choice_a": "Insulate yourself with a 'Rubber-Cloak'", "consequence_a": "Success: You ignore the electrical shocks. (+100 XP)", "choice_b": "Ground the worm with a copper-spike (Str DC 14)", "consequence_b": "Success: You cause a massive short-circuit in its body. (+1 Progress)", "convergence": "The Prime-Worm explodes in a shower of sparks and iron-filings."},
            {"turn": 7, "narrative": "The swarm scatters with the death of their leader. The granary is a mess of spilled grain and mangled metal.", "choice_a": "Help the workers salvage the grain (Endurance DC 13)", "consequence_a": "Success: You save 60% of the winter supply. (+5 Morale)", "choice_b": "Harvest the Prime-Worm's Golden Shell", "consequence_b": "Success: You gain a 'Gold-Obsidian Curio' (Value: 300g). (+1 Loot)", "convergence": "The Granary-Manager arrives, offering you a 'Life-Long Voucher' for bread."},
            {"turn": 8, "narrative": "The Manager reveals the worms weren't natural—they were 'Engineered' to target this specific granary.", "choice_a": "Investigate the shipping logs (Int DC 14)", "consequence_a": "Success: You trace the worms back to the 'Warp-Docks'. (+1 Intel)", "choice_b": "Search the ruins for a 'Control-Disk' (Perc DC 14)", "consequence_b": "Success: You find a small, buzzing device in the debris. (+1 Secret)", "convergence": "You hand the evidence to the local Magistrate."},
            {"turn": 9, "narrative": "The Magistrate rewards you with a 'Defender's Medal' and a bag of 'Spark-Rice'.", "choice_a": "Accept the reward", "consequence_a": "Success: You are now a recognized protector of the food supply. (+5 Reputation)", "choice_b": "Decline and ask for the Prime-Worm's heart", "consequence_b": "Success: You gain a 'Saw-Heart Engine'. (+1 Gear)", "convergence": "The granary is reinforced with stone walls to prevent future attacks."},
            {"turn": 10, "narrative": "The smell of fresh bread from the saved grain fills the air. It's the smell of survival.", "choice_a": "Eat a warm loaf", "consequence_a": "Success: You feel remarkably healthy. (+1 Luck)", "choice_b": "Train the guards in 'Worm-Detection'", "consequence_b": "Success: You increase local security. (+1 Rep)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Rust-Worms' feast was stopped, but the sabotage suggests a 'Food-War' is brewing between the wards.",
        "loot_table": ["Gold-Obsidian Curio", "Harpoon-Launcher", "Saw-Heart Engine", "600 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Silos destroyed. -10 Resources and bread prices double for a month."}
    },
    {
        "id": "SQ-18",
        "title": "The Weaver's Reflection",
        "xp_reward": 900,
        "prerequisites": "None",
        "description": "A 'Mirrored-Pool' in the High-Forest is showing things that haven't happened yet. The Weaver wants a look.",
        "turns": [
            {"turn": 1, "narrative": "The Mirrored-Pool is a perfect circle of liquid silver, surrounded by trees made of white bone. The water doesn't reflect the sky; it reflects a city on fire, and then, a city made of gold.", "choice_a": "Peer into your own future (Wis Save DC 13)", "consequence_a": "Success: You see yourself standing atop a mountain of books. (+1 Secret)", "choice_b": "Toss a 'Truth-Coin' into the water", "consequence_b": "Success: The water ripples, revealing a map to a hidden temple. (+1 Lore)", "convergence": "A 'Reflection' of yourself—made of starlight and shadow—steps out of the pool."},
            {"turn": 2, "narrative": "The Reflection is beautiful and terrifying. It doesn't move like you; it moves with a fluid, pre-determined grace. 'The threads are tangled,' it whispers.", "choice_a": "Ask about the 'Tangle' (Char DC 13)", "consequence_a": "Success: It reveals that a 'Scourge-Anchor' is buried beneath the pool. (+1 Progress)", "choice_b": "Challenge the Reflection to a duel (Atk DC 14)", "consequence_b": "Success: You exchange blows, each one echoing in your mind. (+1 Progress)", "convergence": "The trees around the pool begin to weep a violet sap that tastes like electricity."},
            {"turn": 3, "narrative": "The sap is attracting 'Void-Butterflies'—tiny, flickering insects that eat the 'Possibilities' of the future. The pool's reflection is becoming blurry.", "choice_a": "Purify the sap with 'Holy-Fire' (Religo DC 14)", "consequence_a": "Success: You clear the air. (+100 XP)", "choice_b": "Capture a butterfly in a jar (Dex DC 14)", "consequence_b": "Success: You gain a 'Butterfly of Fate'. (+1 Loot)", "convergence": "The Reflection points to the center of the pool. A 'Logic-Node' is rising from the silver depths."},
            {"turn": 4, "narrative": "The Logic-Node is a complex, clockwork sphere that dictates the 'Probabilities' of the region. It's being choked by a 'Scourge-Vine'.", "choice_a": "Untangle the vine (Dex DC 15)", "consequence_a": "Success: You restore the proper flow of time. (+1 Progress)", "choice_b": "Burn the vine with 'Incendiary-Oil'", "consequence_b": "Success: The vine shrieks and withers, but the Node is slightly charred. (+1 Progress)", "convergence": "The Reflection merges back with the pool, leaving behind its 'Star-Cloak' on the bank."},
            {"turn": 5, "narrative": "The Forest is silent now. The sap has stopped weeping. You feel a strange, hollow sensation in your chest, as if a part of your future was just deleted.", "choice_a": "Meditate by the pool (Wis DC 14)", "consequence_a": "Success: You regain your sense of destiny. (+100 XP)", "choice_b": "Dive into the pool to see the Anchor (Str DC 15)", "consequence_b": "Success: You find a 'Silver-Vessel' at the bottom. (+1 Loot)", "convergence": "A 'Forest-Spirit'—a deer with antlers of crystal—emerges from the white trees."},
            {"turn": 6, "narrative": "The Spirit is the guardian of the pool. It's angry that you've 'touched' the future. It charges, its antlers glowing with a blinding white light.", "choice_a": "Soothe the Spirit (Nature DC 15)", "consequence_a": "Success: It bow its head, allowing you to pass. (+1 Progress)", "choice_b": "Dodge the charge (Dex DC 14)", "consequence_b": "Success: You avoid the lethal antlers. (+1 Progress)", "convergence": "The Spirit dissolves into a thousand white petals, leaving behind a 'Crystal-Antler-Shard'."},
            {"turn": 7, "narrative": "You're holding the Star-Cloak and the Shard. The pool is now reflecting the 'Real' world—a group of Council Guards approaching your position.", "choice_a": "Hide in the white trees (Stealth DC 14)", "consequence_a": "Success: The guards pass by without seeing you. (+1 Progress)", "choice_b": "Stand your ground and explain your presence", "consequence_b": "Success: They recognize you as a hero of the state. (+1 Progress)", "convergence": "The Guard-Captain offers to escort you back to the city, but he's looking at the Star-Cloak with greed."},
            {"turn": 8, "narrative": "The Captain hints that the Star-Cloak could 'buy a lot of favors' in the High-Ward. He's subtly threatening to arrest you for 'Treason against Time'.", "choice_a": "Offer him a bribe (Deception DC 13)", "consequence_a": "Success: He lets you go, but you lose a 'Truth-Coin'. (+1 Secret)", "choice_b": "Refuse and cite the 'Weaver's Law'", "consequence_b": "Success: He backs down, fearing the divine wrath. (+5 Reputation)", "convergence": "You return to the city as the stars begin to fall, each one a tiny miracle."},
            {"turn": 9, "narrative": "You reach the tavern. The Chronicle Weaver is there, waiting in the shadows. He wants to know what you saw in the pool.", "choice_a": "Tell him the truth (Lore DC 14)", "consequence_a": "Success: He rewards you with 'A Weaver's Thread'. (+1 Rare Item)", "choice_b": "Lie about the vision", "consequence_b": "Success: He sees through your lie but respects your privacy. (+1 Luck)", "convergence": "The Star-Cloak begins to fade, its power now a part of your own aura."},
            {"turn": 10, "narrative": "The sun rises. You look in a mirror, and for a split second, your reflection doesn't match your movements. It's smiling.", "choice_a": "Smile back", "consequence_a": "Success: You are in harmony with the future. (+20 Morale)", "choice_b": "Cover the mirror", "consequence_b": "Success: You choose to live in the present. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Weaver's Reflection was a peek behind the curtain of fate. You saved the pool, but the future is no longer a single, straight line.",
        "loot_table": ["Star-Cloak", "Crystal-Antler-Shard", "Butterfly of Fate", "900 Gold"],
        "risk_matrix": {"failure_threshold": 4, "penalty": "Future corrupted. -5 Luck and a permanent 'Unstable' tag (Disadvantage on your next 3 rolls)."}
    }
]

for i, q in enumerate(db):
    for uq in upgraded_batch_2:
        if q['id'] == uq['id']:
            db[i] = uq

p.write_text(json.dumps(db, indent=4), encoding='utf-8')
print("SUCCESS: SQ-15 to SQ-18 upgraded to 10-turn Lush Standard.")
