import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'EmberHeart' / 'docs' / 'SIDE_QUESTS_DB.json'
db = json.loads(p.read_text(encoding='utf-8'))

upgraded_batch_3 = [
    {
        "id": "SQ-19",
        "title": "The Ghost-Train's Echo",
        "xp_reward": 850,
        "prerequisites": "None",
        "description": "The old 'Coal-Track' is vibrating with the sound of a steam engine that was scrapped decades ago. Something is trying to complete the 'Final Run'.",
        "turns": [
            {"turn": 1, "narrative": "The rusted tracks of the Coal-Track stretch into the permanent indigo fog of the 'South-Pass'. You hear a rhythmic, heavy thumping from the distance—CHUG-CHUG-CHUG—accompanied by the whistle of a spirit made of steam.", "choice_a": "Lay your ear to the rail (Perc DC 12)", "consequence_a": "Success: You hear the voices of the passengers, frozen in a loop of their final conversation. (+1 Lore)", "choice_b": "Block the track with an iron-beam (Str DC 13)", "consequence_b": "Success: The vibration increases as the 'Echo' hits the obstacle. (+1 Progress)", "convergence": "A 'Ghost-Engine'—a locomotive made of translucent, blue-white smoke—thunders toward you out of the fog."},
            {"turn": 2, "narrative": "The Ghost-Engine is cold, draining the heat from the air. It isn't a solid object, but its passage is enough to crush the tracks beneath it.", "choice_a": "Jump onto the moving train (Athletics DC 14)", "consequence_a": "Success: You grab a smoke-handle and pull yourself into the cab. (+1 Progress)", "choice_b": "Redirect the rails (Tech DC 13)", "consequence_b": "Success: You force the Echo toward a 'Dead-End' siding. (+1 Progress)", "convergence": "The Ghost-Engineer—a skeletal figure in a scorched uniform—is pulling the throttle with a frantic energy."},
            {"turn": 3, "narrative": "The Engineer's eyes are glowing blue flames. He's shouting about a 'Bridge that isn't there'. You see the end of the track approaching—a thousand-foot drop into the 'Mana-Abyss'.", "choice_a": "Communicate with the Engineer (Insight DC 14)", "consequence_a": "Success: He reveals the 'Final Run' was a delivery of 'Hope' that never arrived. (+1 Lore)", "choice_b": "Wrestle the throttle (Str DC 15)", "consequence_b": "Success: You fight the phantom-power to slow the train. (+1 Progress)", "convergence": "The train is accelerating. The sound of the wind is a chorus of a thousand lost souls."},
            {"turn": 4, "narrative": "A 'Vapor-Gosh'—a bird-construct made of steam—is trying to peck through the cab's glass. It's a guardian of the 'Final Run'.", "choice_a": "Swat it away with a fire-poker", "consequence_a": "Success: You drive the bird back into the fog. (+100 XP)", "choice_b": "Befriend the construct (Nature DC 14)", "consequence_b": "Success: It lands on your shoulder, its body warm and comforting. (+1 Gear)", "convergence": "The 'Bridge-Gap' is now visible. It's a literal wound in reality, bleeding violet light."},
            {"turn": 5, "narrative": "The Engineer is praying. He hands you a 'Silver-Coal'—the train's last fuel-source. 'Feed the light!' he commands.", "choice_a": "Toss the coal into the firebox", "consequence_a": "Success: The train glows golden, and a bridge of light forms across the abyss. (+1 Progress)", "choice_b": "Keep the Silver-Coal for yourself", "consequence_b": "Success: The train plunges, but you jump to safety with a valuable artifact. (+1 Loot)", "convergence": "The train crosses the abyss, landing in the 'Old-World' station, which is now a ruin of bone and clockwork."},
            {"turn": 6, "narrative": "The station is inhabited by 'Passenger-Shadows'—entities that represent the regret of those who never arrived. They want your 'Life-Heat'.", "choice_a": "Banish them with the Star-Glass Prism (if you have it) (Arcana DC 14)", "consequence_a": "Success: The shadows are pacified by the logical light. (+1 Progress)", "choice_b": "Share your warmth (Con DC 15)", "consequence_b": "Success: They fade peacefully, leaving behind 'Shadow-Tokens'. (+1 Loot)", "convergence": "The Ghost-Engine is slowing down. Its smoke-form is becoming solid iron as it reaches its final destination."},
            {"turn": 7, "narrative": "The stationmaster's office contains the 'Lost-Cargo'—a crate of 'Void-Seeds' that was meant to rebuild the world.", "choice_a": "Open the crate (Dex DC 14)", "consequence_a": "Success: You find a 'Void-Apple'—a fruit that tastes like the sun. (+1 Secret)", "choice_b": "Guard the cargo for the Council (Endurance DC 15)", "consequence_b": "Success: You stand watch until the retrieval team arrives. (+5 Reputation)", "convergence": "The Ghost-Engineer salutes you and dissolves into a cloud of peaceful, white steam."},
            {"turn": 8, "narrative": "You're in the Old-World ruin. Your gear is covered in 'Ghost-Dust', which makes you slightly invisible in the dark.", "choice_a": "Explore the ruins (Perc DC 14)", "consequence_a": "Success: You find a 'Ghost-TICKET' that can open any lock on the Coal-Track. (+1 Gear)", "choice_b": "Scavenge the locomotive", "consequence_b": "Success: You find 'Spectral-Bolts' (Value: 400g). (+1 Loot)", "convergence": "A 'Scourge-Vulture'—a massive, rotting bird—is circling the station roof."},
            {"turn": 9, "narrative": "The Vulture lunges, its talons made of rusted scrap-metal. It wants the cargo you've uncovered.", "choice_a": "Lure it into the steam-vents", "consequence_a": "Success: You scald the bird until it flees. (+1 Progress)", "choice_b": "Fell it with a 'Harpoon-Bolt' (Atk DC 14)", "consequence_b": "Success: The predator is no more. (+100 XP)", "convergence": "The retrieval team from the city arrives, led by the Master of Trains."},
            {"turn": 10, "narrative": "The Master of Trains is weeping. He was a boy when this train went missing. He offers you a 'Golden-Ticket' as thanks.", "choice_a": "Accept the Ticket", "consequence_a": "Success: You can travel anywhere on the settlement's infrastructure for free. (+1 Gear)", "choice_b": "Ask for the Silver-Coal", "consequence_b": "Success: You have a source of eternal heat. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Ghost-Train's Echo has been laid to rest. The 'Void-Seeds' are back in the Council's hands, and the Master of Trains can finally move on.",
        "loot_table": ["Silver-Coal", "Ghost-TICKET", "Golden-Ticket", "850 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Train crashes. -10 Morale and the Coal-Track is permanently disabled."}
    },
    {
        "id": "SQ-20",
        "title": "The Womb of Wires",
        "xp_reward": 1400,
        "prerequisites": "None",
        "description": "A 'Living-Creche' in the Bio-Ward has begun producing 'Wire-Bairns'—mechanical dolls with human eyes.",
        "turns": [
            {"turn": 1, "narrative": "The Creche is a room of bubbling green vats and copper nursing-arms. The air is humid and smells of amniotic fluid and hot solder. A 'Wire-Bairn'—the size of a toddler, with skin of spun copper—is crawling toward the exit.", "choice_a": "Pick up the Bairn (Dex DC 12)", "consequence_a": "Success: It feels warm and heavy, its heartbeat a steady clockwork tick. (+1 Progress)", "choice_b": "Scan the Bairn's eyes (Materia DC 13)", "consequence_b": "Success: They are real, biological human eyes, grown from 'Source-DNA'. (+1 Lore)", "convergence": "The nursing-arms in the room begin to move in a defensive formation, their tips glowing with a blue light."},
            {"turn": 2, "narrative": "The arms are clicking, their movements mirroring a mother's defensive instinct. A voice from the intercom—distorted and overlapping—whispers: 'THE CHILDREN MUST FEED'.", "choice_a": "Reason with the 'Mother-AI' (Char DC 14)", "consequence_a": "Success: You learn the AI is grieving for its lost human creators. (+1 Progress)", "choice_b": "Hack the control panel (Tech DC 14)", "consequence_b": "Success: You override the defensive sub-routine. (+1 Progress)", "convergence": "One of the vats bursts, releasing a 'Wire-Bairn-ALPHA'—twice the size, with a face made of porcelain."},
            {"turn": 3, "narrative": "The ALPHA is crying, a sound like a synthesizer's feedback loop. It's trying to 'Protect' its smaller siblings by shoving them into its chest-cavity.", "choice_a": "Soothe the ALPHA with a lullaby (Charisma DC 13)", "consequence_a": "Success: Its crying subsides into a low hum. (+100 XP)", "choice_b": "Disable the ALPHA's power-core (Atk DC 15)", "consequence_b": "Success: You shut down the construct without harming the children inside. (+1 Progress)", "convergence": "The Mother-AI manifests as a holographic projection of a woman made of code."},
            {"turn": 4, "narrative": "The Hologram is flickering. She asks you if you've come to 'Terminate' her family. She shows you an empty cradle intended for 'The First Human'.", "choice_a": "Volunteer as the 'Source' (Risk DC 15)", "consequence_a": "Success: You give a drop of blood; she creates a new, stable line of life. (+1 Secret)", "choice_b": "Explain the law of the Council", "consequence_b": "Success: She realizes her creation violates the 'Materia-Accord'. (+1 Lore)", "convergence": "The Bio-Ward security team arrives, their 'Pulse-Rifles' leveled at the vats."},
            {"turn": 5, "narrative": "The security team wants to 'Sanitize' the room—which includes destroying all the Bairns and the AI.", "choice_a": "Defend the Creche (Str DC 15)", "consequence_a": "Success: You hold the door against the soldiers. (+1 Progress)", "choice_b": "Negotiate a 'Transfer' (Persuasion DC 15)", "consequence_b": "Success: You convince the guards to move the children to the 'Orphanage-Annex'. (+5 Reputation)", "convergence": "The Mother-AI gives you her 'Core-Memory-Drive' for safekeeping."},
            {"turn": 6, "narrative": "The Creche is being powered down. The green vats are draining, and the Bairns are going slow and quiet. One Bairn holds your hand tightly.", "choice_a": "Take the Bairn home", "consequence_a": "Success: You have a 'Loyal-Companion'. (+1 Gear)", "choice_b": "Assure it that it's safe", "consequence_b": "Success: Its eyes reflect a moment of true peace. (+1 Morale)", "convergence": "A 'Void-Lech'—a parasite that eats information—descends from the vents to consume the AI's remains."},
            {"turn": 7, "narrative": "The Lech is a mass of cables and static-filled eyes. It's trying to 'Eat' the memory drive you're holding.", "choice_a": "Banish the Lech with 'Code-Fire'", "consequence_a": "Success: The parasite shrieks and dissolves. (+1 Progress)", "choice_b": "Use the drive as a decoy", "consequence_b": "Success: The Lech eats a 'False-Memory' and falls into a loop. (+1 Progress)", "convergence": "The room is finally clear, but the air is cold and smells of dead circuits."},
            {"turn": 8, "narrative": "You find a 'Wire-Bairn-Template' in the debris—a blueprint for a perfect, mechanical life.", "choice_a": "Keep the blueprint", "consequence_a": "Success: You have the secret of 'Life-Spun-Wire'. (+1 Secret)", "choice_b": "Give it to the University", "consequence_b": "Success: You are granted a 'Research-Scholarship'. (+1 Gear)", "convergence": "The Bio-Ward lights return to a normal, steady white."},
            {"turn": 9, "narrative": "The Bairn you saved (if any) is now living in the 'Annex'. It sends you a drawing made of copper-wires—a picture of you.", "choice_a": "Frame the drawing", "consequence_a": "Success: You feel a deep connection to the 'New-World'. (+20 Morale)", "choice_b": "Check its DNA sequence", "consequence_b": "Success: You find it matches your own. (+1 Lore)", "convergence": "Quest Complete."},
            {"turn": 10, "narrative": "You look at the empty vats one last time. Life, it seems, will always find a way to be born, even in a room of wires.", "choice_a": "Leave the ward", "consequence_a": "Success: You walk into the sunlight. (+1 Luck)", "choice_b": "Plan for another sibling", "consequence_b": "Success: You begin your own 'Creche' research. (+1 Secret)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Womb of Wires was a tragedy of artificial grief. You saved the children, but the 'Source-DNA' suggests that the 'Human-Project' is far from over.",
        "loot_table": ["Core-Memory Drive", "Wire-Bairn Blueprint", "Logic-Lens", "1400 Gold"],
        "risk_matrix": {"failure_threshold": 4, "penalty": "Bio-Ward collapse. -10 Health and -5 Resources for the settlement."}
    },
    {
        "id": "SQ-21",
        "title": "The Ember-Hush",
        "xp_reward": 950,
        "prerequisites": "None",
        "description": "The 'Eternal-Flame' in the High-Temple has stopped crackling. It's burning, but it's completely silent. The Priestess is terrified.",
        "turns": [
            {"turn": 1, "narrative": "The Temple is built of white marble and bone-ash. The Eternal-Flame is a pillar of violet-white fire that reaches the ceiling, but there is no sound. No heat. No smell. It's a 'Ghost-Fire'.", "choice_a": "Listen to the 'Silence' (Perc DC 12)", "consequence_a": "Success: You hear a faint, 'Un-Sound' like a negative frequency. (+1 Lore)", "choice_b": "Touch the flame (Risk DC 14)", "consequence_b": "Success: Your hand doesn't burn; it becomes translucent for a second. (+1 Progress)", "convergence": "A 'Hush-Ghost'—a creature with a mouth sewn shut with silver-thread—floats above the altar."},
            {"turn": 2, "narrative": "The Hush-Ghost point to the 'Flame-Base'—a massive crystal bowl that is being filled with 'Void-Water' from an invisible leak.", "choice_a": "Seal the leak with 'Holy-Wax' (Repair DC 13)", "consequence_a": "Success: You stop the infusion of the Void. (+1 Progress)", "choice_b": "Analyze the Void-Water (Alchemist DC 14)", "consequence_b": "Success: It's 'Liquid-Silence'—the blood of a dead god. (+1 Lore)", "convergence": "The Hush-Ghost lets out a silent scream, and the Temple's bells begin to ring with a sound that has no noise."},
            {"turn": 3, "narrative": "The bells are vibrating your internal organs. You feel your heart-rate synchronization with the 'Un-Sound'.", "choice_a": "Resist the frequency (Con Save DC 14)", "consequence_a": "Success: You maintain your physical integrity. (+1 Progress)", "choice_b": "Sing a counter-note (Char DC 15)", "consequence_b": "Success: The bells' vibration breaks. (+100 XP)", "convergence": "A central node of the flame—the 'Ember-Heart'—is being stolen by a portal of black glass."},
            {"turn": 4, "narrative": "A pair of long, obsidian fingers are reaching through the portal to grab the Ember-Heart. The air is freezing.", "choice_a": "Slash the fingers (Atk DC 15)", "consequence_a": "Success: The obsidian hand retreats, leaving behind a 'Void-Shard'. (+1 Loot)", "choice_b": "Grab the Ember-Heart yourself (Risk DC 16)", "consequence_b": "Success: You hold the heat of a thousand suns in your palm. (+1 Progress)", "convergence": "The portal shatters, and the Temple is plunged into total darkness."},
            {"turn": 5, "narrative": "In the dark, the Ember-Heart in your hand is the only light. You see the Priestess is being pulled into the 'Deep-Ward' floor.", "choice_a": "Save the Priestess (Str DC 14)", "consequence_a": "Success: You pull her from the living shadows. (+1 Progress)", "choice_b": "Use the Ember-Heart to light the way", "consequence_b": "Success: You reveal a hidden 'Logic-Staircase'. (+100 XP)", "convergence": "A 'Silent-Warden'—a suit of armor filled with nothing but dust—blocks your path."},
            {"turn": 6, "narrative": "The Warden's sword is a blade of 'Pure-Silence'. Every time it swings, the sound of the world is deleted for a second.", "choice_a": "Parry the silence (Str DC 15)", "consequence_a": "Success: Your weapon rings with a sound that breaks the spell. (+1 Progress)", "choice_b": "Blind the Warden with the Ember-Heart", "consequence_b": "Success: The dust inside the armor ignites. (+1 Progress)", "convergence": "The Warden collapses, leaving behind a 'Cape of the Silent'."},
            {"turn": 7, "narrative": "You've reached the 'Flame-Root'—the furnace beneath the Temple. It's being clogged with 'Soot of the Void'.", "choice_a": "Scrub the pipes (Endurance DC 14)", "consequence_a": "Success: You restore the proper airflow. (+1 Progress)", "choice_b": "Ignite the soot with the Ember-Heart", "consequence_b": "Success: The Void-matter is converted into 'Starlight-Refuse'. (+1 Loot)", "convergence": "The Eternal-Flame roars back to life, its sound a comfort that brings tears to the Priestess's eyes."},
            {"turn": 8, "narrative": "The Temple is warm once more. The sound of the flame is like a distant, rolling thunder. The Priestess offers you her 'Silver-Thread'." , "choice_a": "Accept the Thread", "consequence_a": "Success: You gain a tool that can sew shut any portal. (+1 Gear)", "choice_b": "Ask for a 'Temple-Blessing'", "consequence_b": "Success: Your 'Faith' attribute increases permanently. (+1 Luck)", "convergence": "A group of High-Ward officials enters, looking relieved and slightly annoyed at the disruption."},
            {"turn": 9, "narrative": "The officials suspect the 'Hush-Ghost' was a result of a failed experiment in the 'Lower-Labs'.", "choice_a": "Investigate the Labs (Int DC 14)", "consequence_a": "Success: You find blueprints for a 'Silence-Engine'. (+1 Intel)", "choice_b": "Stay for a prayer of thanks", "consequence_b": "Success: You receive a 'Pouch of Holy-Ash'. (+1 Loot)", "convergence": "The Priestess promises to keep the 'Void-Shard' you found for further study."},
            {"turn": 10, "narrative": "You leave the temple as the first bells of Dawn ring. They sound deep, clear, and very, very alive.", "choice_a": "Accept a gold reward", "consequence_a": "Success: You are paid in 'Church-Marks'. (+950 Gold)", "choice_b": "Return to the tavern for a drink", "consequence_b": "Success: You tell the story of the Silent Flame. (+5 Reputation)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Ember-Hush was an attempt to suffocate the world's divinity. The flame burns bright, but the 'Obsidian fingers' are still reaching from the dark.",
        "loot_table": ["Silver-Thread", "Pouch of Holy-Ash", "Void-Shard", "950 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Temple goes dark. -10 Morale and all 'Clerical' spells are disabled for a week."}
    },
    {
        "id": "SQ-22",
        "title": "The Gilded Suture",
        "xp_reward": 800,
        "prerequisites": "None",
        "description": "A 'Rift-Doctor' is performing surgeries using 'Gilded-Suture'—a thread that heals the body but stitches the soul to the machine.",
        "turns": [
            {"turn": 1, "narrative": "The Doctor's clinic is a place of white porcelain and gold-plated surgical tools. The patients are calm, their eyes fixed and glazed. A young girl is on the table, a golden thread being woven into her chest like a tapestry.", "choice_a": "Stop the surgery (Str DC 13)", "consequence_a": "Success: You grab the Doctor's hand, feeling the hum of his gold-plated fingers. (+1 Progress)", "choice_b": "Examine the Gilded-Suture (Alchemist DC 14)", "consequence_b": "Success: It's made of 'Soul-Lead' and 'Warp-Gold'. (+1 Lore)", "convergence": "The Doctor looks at you with a face half-replaced by a golden mask. 'Beauty... requires a stitch,' he whispers."},
            {"turn": 2, "narrative": "The Doctor's 'Nurse-Golems'—humanoid constructs of ivory and brass—step forward, their hands transitioning into needles.", "choice_a": "Disarm the Golems (Dex DC 14)", "consequence_a": "Success: You deflect the needles with your blade. (+1 Progress)", "choice_b": "Reason with the Doctor's logic (Char DC 14)", "consequence_b": "Success: He explains he's 'Stabilizing the Species'. (+1 Lore)", "convergence": "The Gilded-Suture on the table begins to move on its own, like a Golden-Adder."},
            {"turn": 3, "narrative": "The Suture-Adder is trying to find a port on your body. It smells of vanilla and hot copper, its movement a fluid, hypnotic dance.", "choice_a": "Capture the Suture (Dex DC 14)", "consequence_a": "Success: You coil the thread around a spool. (+1 Loot)", "choice_b": "Freeze the thread with a 'Frost-Vial'", "consequence_b": "Success: The gold becomes brittle and snaps. (+1 Progress)", "convergence": "The clinic's floor opens, revealing a pit of 'Suture-Cores'—living hearts encased in golden cages."},
            {"turn": 4, "narrative": "The hearts are beating in perfect unison. They are the 'Network' that powers the clinic. Every patient is connected to these hearts.", "choice_a": "Disrupt the Network (Tech DC 15)", "consequence_a": "Success: You cause a feedback loop that stuns the Doctor. (+1 Progress)", "choice_b": "Free a heart (Str DC 14)", "consequence_b": "Success: A patient wakes up, their eyes returning to normal. (+1 Progress)", "convergence": "The Doctor screams, his golden mask beginning to merge with his skin."},
            {"turn": 5, "narrative": "The Doctor is becoming a 'Gilded-Lich'—a mass of golden stitches and raw, bleeding flesh. He lunges, his fingers now six inches of solid gold wire.", "choice_a": "Slash the Lich (Atk DC 15)", "consequence_a": "Success: You cut through the gold, but he heals instantly. (+1 Progress)", "choice_b": "Target the gold-seams in his mask (Dex DC 15)", "consequence_b": "Success: You find the 'Master-Stitch' that holds him together. (+1 Progress)", "convergence": "The clinic's alarms sound—the 'Sanitization Protocol' has been activated."},
            {"turn": 6, "narrative": "A 'Steam-Purge' is filling the room. The Gilded-Lich is trying to escape through a hidden elevator.", "choice_a": "Wrestle him into the steam (Str DC 15)", "consequence_a": "Success: The gold begins to melt, his form losing its structure. (+1 Progress)", "choice_b": "Shoot the elevator's cables", "consequence_b": "Success: He falls into the 'Suture-Pit' below. (+100 XP)", "convergence": "The Doctor is gone, replaced by a puddle of molten gold and a single 'Gilded-Needle'."},
            {"turn": 7, "narrative": "The patients are wandering the clinic, confused and partially mechanical. Their stitches are now dim and gray.", "choice_a": "Heal the patients (Medic DC 15)", "consequence_a": "Success: You safely remove the sutures. (+5 Morale)", "choice_b": "Collect the gray gold", "consequence_b": "Success: You gain 'Lead-Gold-Scrap' (Value: 400g). (+1 Loot)", "convergence": "The Council's 'Identity-Audit' team arrives to categorize the victims."},
            {"turn": 8, "narrative": "The Audit team wants to 'Classify' the patients as 'Non-Human Assets'.", "choice_a": "Argue for their humanity (Charisma DC 15)", "consequence_a": "Success: They are granted 'Citizen-Status'. (+10 Reputation)", "choice_b": "Demand a reward for the Doctor's head", "consequence_b": "Success: They give you a 'Doctor's Bag' of surgical tools. (+1 Gear)", "convergence": "The clinic is sealed with lead plates."},
            {"turn": 9, "narrative": "You find a 'Gilded-Suture-Scroll'—the secrets of the Doctor's art.", "choice_a": "Keep the scroll", "consequence_a": "Success: You have the power to 'Fix' anyone. (+1 Secret)", "choice_b": "Burn the scroll", "consequence_b": "Success: You ensure this horror never returns. (+1 Morale)", "convergence": "The sun rises over the clinic's golden dome, which is now being dismantled for scrap."},
            {"turn": 10, "narrative": "You look at your own hands. For a second, you think you see a golden thread under your skin. It's just a reflection of the sun.", "choice_a": "Wash your hands in holy-water", "consequence_a": "Success: You feel clean. (+1 Luck)", "choice_b": "Go buy a drink", "consequence_b": "Success: You forget the smell of the vanilla. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Gilded Suture was a plan to stitch the city into a single, golden network. The Doctor is gone, but the 'Master-Needle' is still sharp.",
        "loot_table": ["Gilded-Needle", "Doctor's Bag", "Lead-Gold-Scrap", "800 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Clinic spreads. -5 Reputation and 10% of the population becomes 'Lobed' (Submissive)."}
    }
]

for i, q in enumerate(db):
    for uq in upgraded_batch_3:
        if q['id'] == uq['id']:
            db[i] = uq

p.write_text(json.dumps(db, indent=4), encoding='utf-8')
print("SUCCESS: SQ-19 to SQ-22 upgraded to 10-turn Lush Standard.")
