import json
from pathlib import Path

p = Path(__file__).resolve().parent / 'EmberHeart' / 'docs' / 'SIDE_QUESTS_DB.json'
db = json.loads(p.read_text(encoding='utf-8'))

final_batch = [
    {
        "id": "SQ-23",
        "title": "The Hollow-Men's Choir",
        "xp_reward": 800,
        "prerequisites": "None",
        "description": "A group of 'Hollow-Men'—people whose souls were harvested by the Scourge—have gathered in the 'Shattered-Square' to sing.",
        "turns": [
            {"turn": 1, "narrative": "The Shattered-Square is a wasteland of white rubble and tilted statues. The Hollow-Men stand in a circle, their mouths open and perfectly still. The sound coming from them is a harmonic, vibrating hum that makes the loose stones on the ground dance and spin.", "choice_a": "Join the circle to feel the frequency (Wis DC 13)", "consequence_a": "Success: You feel a sense of 'Collective-Peace'. (+1 Secret)", "choice_b": "Disperse the gathering before it's too late (Str DC 12)", "consequence_b": "Success: You shove a Hollow-Man, and the hum falters. (+1 Progress)", "convergence": "A 'Choir-Master'—a Hollow-Man with a crown of rusted barbed-wire—steps to the center."},
            {"turn": 2, "narrative": "The Master's hum is deeper, reaching into the base of your skull. He's trying to tune the whole city to the 'Void-Frequency'.", "choice_a": "Counter-sing with a 'Song of Life' (Char DC 14)", "consequence_a": "Success: You break the Master's rhythm. (+1 Progress)", "choice_b": "Strike the Master's wire-crown (Atk DC 14)", "consequence_b": "Success: The crown snaps, and the hum turns into a scream. (+100 XP)", "convergence": "The ground beneath the Square begins to tilt and float—gravity is being unmade by the sound."},
            {"turn": 3, "narrative": "You're floating in a cloud of white dust. The Hollow-Men are ascending, their bodies becoming translucent. 'The Weaver... needs... the notes,' the Master whispers.", "choice_a": "Grab a floating Hollow-Man (Str DC 14)", "consequence_a": "Success: You anchor them to the ground. (+1 Progress)", "choice_b": "Analyze the 'Void-Frequency' (Arcana DC 14)", "consequence_b": "Success: It's the coordinates to the 'World-Core'. (+1 Lore)", "convergence": "A 'Frequency-Siphon'—a device of glass and copper—appears in the air, drinking the sound."},
            {"turn": 4, "narrative": "The Siphon is being used by a 'Shadow-Caster'—a man in a high-ward uniform. He's stealing the Hollow-Men's last essence.", "choice_a": "Smash the Siphon (Atk DC 15)", "consequence_a": "Success: The essences return to their hosts. (+1 Progress)", "choice_b": "Confront the Caster", "consequence_b": "Success: He reveals he's 'Harvesting' for the Council. (+1 Secret)", "convergence": "The Square collapses back to the earth with a violent jolt. The Hollow-Men are now just piles of gray dust."},
            {"turn": 5, "narrative": "The dust is swirling into the shape of a 'Grief-Giant'—a massive entity made of pulverized bone and silver-regret.", "choice_a": "Banish the Giant (Religo DC 15)", "consequence_a": "Success: The entity dissolves into a cool rain. (+1 Progress)", "choice_b": "Strike the Giant's 'Core-Stone' (Atk DC 14)", "consequence_b": "Success: You shatter the source of its power. (+1 Progress)", "convergence": "The Square is silent. The Shadow-Caster has vanished, leaving behind a 'Stolen-Essence-Jar'."},
            {"turn": 6, "narrative": "The Jar is pulsing with a soft, blue light. Inside are the voices of the Hollow-Men—their songs, their names, their lives.", "choice_a": "Open the Jar to free the souls", "consequence_a": "Success: The air is filled with a thousand whispers of 'Thank You'. (+10 Morale)", "choice_b": "Take the Jar to the Temple of Flame", "consequence_b": "Success: The Priestess can use the essence for 'Re-Souling'. (+1 Gear)", "convergence": "A 'Hollow-King'—a legendary figure from the Old-Wars—rises from the dust."},
            {"turn": 7, "narrative": "The King has no face, only a void where his heart should be. He offers you his 'Shattered-Blade'.", "choice_a": "Accept the Blade", "consequence_a": "Success: You gain a weapon that can cut through any lie. (+1 Gear)", "choice_b": "Decline and offer him a 'Truth-Coin'", "consequence_b": "Success: He finds a moment of clarity and fades away. (+5 Reputation)", "convergence": "The sun sets over the Shattered-Square, painting the ruins in a blood-red light."},
            {"turn": 8, "narrative": "You find a 'Choir-Sheet'—a map of the city hidden in musical notation.", "choice_a": "Study the Sheet (Int DC 14)", "consequence_a": "Success: You find a 'Void-Tunnel' beneath the High-Ward. (+1 Intel)", "choice_b": "Give the Sheet to the Tavern-Bard", "consequence_b": "Success: He turns the struggle into a 'Legendary Ballad'. (+1 Fame)", "convergence": "The Shadow-Caster's tracks lead into the sewers."},
            {"turn": 9, "narrative": "In the sewers, you find a 'Soul-Press'—a machine used to create Hollow-Men.", "choice_a": "Destroy the Press (Str DC 15)", "consequence_a": "Success: You prevent any more souls from being stolen. (+5 Morale)", "choice_b": "Tamper with the Press (Tech DC 14)", "consequence_b": "Success: It now 'Screams' whenever a Shadow-Caster uses it. (+1 Secret)", "convergence": "The Choir's echo remains in the Square, a hauntingly beautiful reminder of what was lost."},
            {"turn": 10, "narrative": "You stand in the center of the ruins. The air feels lighter, the silence no longer heavy with grief.", "choice_a": "Accept a gold reward from the survivors", "consequence_a": "Success: They give you everything they have. (+800 Gold)", "choice_b": "Leave without payment", "consequence_b": "Success: You are known as a 'Bringer of Peace'. (+10 Rep)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Hollow-Men's Choir was a call for help from the very foundations of the world. You answered it, but the 'Shadow-Casters' are still looking for more voices.",
        "loot_table": ["Stolen-Essence-Jar", "Shattered-Blade", "Choir-Sheet", "800 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Square consumed. -10 Morale and the 'Grief-Giant' wanders the city for 3 days."}
    },
    {
        "id": "SQ-24",
        "title": "The Glass-Walker's Path",
        "xp_reward": 850,
        "prerequisites": "None",
        "description": "A 'Glass-Walker'—a traveler who can walk on any surface—is stuck in a 'Mirror-Loop' in the North-Ward.",
        "turns": [
            {"turn": 1, "narrative": "The Mirror-Loop is a zone where every window and puddle acts as a portal. The Glass-Walker is a man in a coat of silver-scales, frantically jumping from his reflection in a baker's shop to a reflection in a rain-barrel. He's trapped in a ten-second loop of his own panic.", "choice_a": "Break the primary mirror (Str DC 12)", "consequence_a": "Success: You shatter the baker's window, and the Walker falls into the real world. (+1 Progress)", "choice_b": "Stabilize the loop with 'Void-Glue' (Tech DC 13)", "consequence_b": "Success: You slow the transitions, giving him time to breathe. (+1 Progress)", "convergence": "The Walker's reflections begin to detach and walk on the walls of the street."},
            {"turn": 2, "narrative": "There are now six Glass-Walkers, all screaming in synchronized harmony. They are trying to 'Pull the World into the Glass'.", "choice_a": "Identify the 'Original' Walker (Insight DC 14)", "consequence_a": "Success: You spot the one whose scales are slightly tarnished. (+1 Progress)", "choice_b": "Blaze the area with light", "consequence_b": "Success: The reflections are blinded and retreat into the shadows. (+100 XP)", "convergence": "The street begins to turn into a material as fragile as glass—with every step, you hear a crack beneath your boots."},
            {"turn": 3, "narrative": "A 'Refraction-Horror'—a entity made of thousand-faceted diamonds—emerges from a puddle. It's beautiful and sharp, its movements a light-show of lethal intensity.", "choice_a": "Strike the facets (Atk DC 15)", "consequence_a": "Success: You chip away its symmetry. (+1 Progress)", "choice_b": "Use a mirror to reflect its own beam (Dex DC 15)", "consequence_b": "Success: The Horror is blinded by its own light. (+1 Progress)", "convergence": "The Glass-Walker hands you his 'Silver-Sandal'. 'Step where I step!' he cries."},
            {"turn": 4, "narrative": "With the Silver-Sandal, the 'Glass-World' becomes visible. You are walking on a bridge of light over an abyss of 'Raw-Data'.", "choice_a": "Cross the bridge (Dex DC 14)", "consequence_a": "Success: You reach the 'Mirror-Core'—a floating, hexagonal prism. (+1 Progress)", "choice_b": "Look into the 'Raw-Data' (Int DC 15)", "consequence_b": "Success: You see the 'Code' of the city's foundation. (+1 Lore)", "convergence": "A 'Reflection-Stalker'—a shadow made of broken glass—appears behind you."},
            {"turn": 5, "narrative": "The Stalkers are trying to trip you into the abyss. Their touch is cold and leaves 'Glass-Splinters' in your mind.", "choice_a": "Reinforce your 'Self-Image' (Wis Save DC 14)", "consequence_a": "Success: You resist the identity-drain. (+100 XP)", "choice_b": "Shatter the bridge behind you", "consequence_b": "Success: You cut off their pursuit. (+1 Progress)", "convergence": "You reach the Mirror-Core. It's humming with the sound of a thousand people talking at once."},
            {"turn": 6, "narrative": "The Core is a 'Logic-Vault'—it's storing the memories of the North-Ward. It's been 'Corrupted' by a 'Void-Worm'.", "choice_a": "Extract the Void-Worm (Dex DC 15)", "consequence_a": "Success: You pull the purple parasite from the clockwork. (+1 Loot)", "choice_b": "Purify the Core with 'Holy-Water'", "consequence_b": "Success: The memories return to their owners. (+10 Morale)", "convergence": "The Mirror-Loop collapses. You and the Walker fall back onto the cobblestones of the North-Ward."},
            {"turn": 7, "narrative": "The Glass-Walker is unconscious, his coat of scales now dull and gray. He's clutching a 'Mirror-Compass'.", "choice_a": "Take the Compass", "consequence_a": "Success: You gain a tool that points to the nearest rift. (+1 Gear)", "choice_b": "Revive the Walker (Medic DC 13)", "consequence_b": "Success: He thanks you and offers to be your 'Scout'. (+5 Reputation)", "convergence": "A 'Glass-Sanitizer' squad from the High-Ward arrives, carrying steam-hoses and iron-hammers."},
            {"turn": 8, "narrative": "They want to 'Shatter' the whole street to ensure the loop is truly gone.", "choice_a": "Interpose yourself (Str DC 14)", "consequence_a": "Success: You protect the residents' property. (+5 Morale)", "choice_b": "Negotiate a 'Precision-Clean' (Persuasion DC 14)", "consequence_b": "Success: They only break the necessary windows. (+1 Progress)", "convergence": "You find a 'Shard of True-Memory' in the debris."},
            {"turn": 9, "narrative": "The Shard shows you a vision of a 'Glass-City' beneath the ice of the North-Pass.", "choice_a": "Note the location (Int DC 14)", "consequence_a": "Success: You have a new destination. (+1 Lore)", "choice_b": "Give the Shard to the Chronicle Weaver", "consequence_b": "Success: He gives you 'The Weaver's Glass-Eye'. (+1 Rare Item)", "convergence": "The North-Ward is safe for now, the windows once again reflecting only the sky."},
            {"turn": 10, "narrative": "You walk away from the street. Every time you pass a mirror, you check to see if your reflection is still following. So far, it is.", "choice_a": "Accept a bag of silver coins", "consequence_a": "Success: You are paid 850 gold. (+850 Gold)", "choice_b": "Rest at the Tavern", "consequence_b": "Success: You dream of a world made of diamonds. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Glass-Walker's Path was a leak from the 'Mirror-Plane'. The loop is closed, but the 'Refraction-Horror' suggests a larger geometry is at work.",
        "loot_table": ["Mirror-Compass", "Void-Worm Jar", "Silver-Sandal", "850 Gold"],
        "risk_matrix": {"failure_threshold": 3, "penalty": "Street becomes 'Fragile'. -2 Defense and a permanent risk of 'Glass-Cuts' (-5 Health) for anyone walking here."}
    },
    {
        "id": "SQ-25",
        "title": "The Ember's Final Breath",
        "xp_reward": 2000,
        "prerequisites": "None",
        "description": "The 'Great-Ember'—the source of the city's warmth—is dying. You must enter the 'Core-Vault' for a final stand.",
        "turns": [
            {"turn": 1, "narrative": "The Core-Vault is a place of white heat and blinding light. The 'Great-Ember' is a sphere of liquid fire the size of a house, vibrating with a tone that signifies its impending collapse. The air is so hot it scorches your lungs.", "choice_a": "Identify the cause of the decay (Int DC 13)", "consequence_a": "Success: You find 'Void-Rust' on the primary heat-cables. (+1 Progress)", "choice_b": "Channel your own mana into the Ember (Risk DC 15)", "consequence_b": "Success: You stabilize the core for a few seconds. (+100 XP)", "convergence": "A 'Scourge-Titan'—a titan made of solidified shadow and rusted iron—steps into the vault."},
            {"turn": 2, "narrative": "The Titan is the source of the decay. It's 'Eating' the heat to empower its own shadow-form. It roars, a sound that vibrates the very bedrock of the city.", "choice_a": "Strike the Titan's iron-shield (Str DC 15)", "consequence_a": "Success: You create a breach in its defense. (+1 Progress)", "choice_b": "Use the 'Star-Prism' to burn through the shadow", "consequence_b": "Success: The light carves a path through the beast's chest. (+1 Progress)", "convergence": "The Titan lunges, its shadow-claws reaching for the Ember itself."},
            {"turn": 3, "narrative": "You must stand between the Titan and the Ember. The heat is reaching a 'White-Line' critical point. The vault walls are starting to melt into slag.", "choice_a": "Hold the line (Endurance DC 16)", "consequence_a": "Success: You take the Titan's full force, protecting the city's heart. (+1 Progress)", "choice_b": "Unleash a 'Mana-Burst' (Arcana DC 15)", "consequence_b": "Success: You push the Shadow back, but lose some of your own life-essence. (+100 XP)", "convergence": "The Titan collapses, its shadow-form burning away in the intense heat of the Ember."},
            {"turn": 4, "narrative": "The Titan is dead, but the Ember is still unstable. The Priestess's voice crackles over the comms: 'It's going to blow! Use the First-Shard!'", "choice_a": "Apply the First-Shard to the Core (Dex DC 15)", "consequence_a": "Success: The Ember stabilizes, its color returning to a steady, warm orange. (+50 Morale)", "choice_b": "Evacuate the Vault and let it blow (Evil Action)", "consequence_b": "Success: You escape, but the city is plunged into eternal frost. (-50 Reputation)", "convergence": "The vault is quiet. The 'Great-Ember' is breathing steadily once more."},
            {"turn": 5, "narrative": "You've saved the city, but you're badly burned. You see a 'Vision' of the Weaver standing in the fire, smiling. She hands you a 'Sun-Amulet'.", "choice_a": "Accept the Amulet", "consequence_a": "Success: You gain permanent resistance to Void-damage. (+1 Rare Gear)", "choice_b": "Refuse and ask for the city's safety", "consequence_b": "Success: She grants the settlement a 'Golden-Age' (Bonus resources for a month). (+100 Reputation)", "convergence": "You emerge from the vault as a legend. The city is warm. The sun is gold."},
            {"turn": 6, "narrative": "The High-Ward holds a celebration in your honor. A statue is commissioned in the central plaza.", "choice_a": "Accept the glory", "consequence_a": "Success: You are now a 'High-Councilor'. (+10 Reputation)", "choice_b": "Disappear into the wastes", "consequence_b": "Success: Your legend becomes part of the city's spirit. (+1 Fame)", "convergence": "You find a 'Vial of Ember-Sap' in your pocket—a gift from the fire."},
            {"turn": 7, "narrative": "The Ember-Sap can be used to forge the 'Ultimate-Weapon'.", "choice_a": "Go to the Black-Forge", "consequence_a": "Success: You forge 'Ember-Bane'. (+1 Legendary Weapon)", "choice_b": "Save it for the Winter-Seed", "consequence_b": "Success: You ensure the settlement's survival for decades. (+100 Resources)", "convergence": "The night is clear, and for the first time, you don't feel the cold."},
            {"turn": 8, "narrative": "A 'Scourge-Lord' sends you a message: 'The Ember is just one spark. The dark is infinite.'", "choice_a": "Shred the message", "consequence_a": "Success: You remain defiant. (+1 Morale)", "choice_b": "Keep it for study (Int DC 14)", "consequence_b": "Success: You find a weakness in the Lord's own shadow. (+1 Lore)", "convergence": "The 'Ember's Final Breath' was actually its first true breath in centuries."},
            {"turn": 9, "narrative": "You sit on the battlements, looking out at the Scourge-Fog. It seems a little thinner today.", "choice_a": "Accept your payment (2000 Gold)", "consequence_a": "Success: You are wealthy beyond measure. (+2000 Gold)", "choice_b": "Donate the gold to the Bio-Ward", "consequence_b": "Success: You are a saint of the wastes. (+20 Reputation)", "convergence": "The sun rises over a city that finally knows peace."},
            {"turn": 10, "narrative": "You close your eyes and feel the warmth. It's the warmth of home. The warmth of a future you fought for.", "choice_a": "Rest", "consequence_a": "Success: You have earned it. (+1 Luck)", "choice_b": "Plan the next expedition", "consequence_b": "Success: The journey continues. (+1 Progress)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The siege of the Southern Gate is over. The settlement has survived its darkest hour, and the name of the 'Ember' will be sung for generations.",
        "loot_table": ["Sun-Amulet", "Ember-Bane", "Vial of Ember-Sap", "2000 Gold"],
        "risk_matrix": {"failure_threshold": 5, "penalty": "Settlement destroyed. The campaign ends in darkness."}
    },
    {
        "id": "SQ-30",
        "title": "The Fog-Watcher's Lantern",
        "xp_reward": 750,
        "prerequisites": "None",
        "description": "The outer-perimeter signal lantern has gone dark during a thick Scourge-fog. Without it, the scout ships are blind.",
        "turns": [
            {"turn": 1, "narrative": "The fog is so thick you can't see your own hand. It's cold, damp, and smells of wet ash. The path to the signal tower is barely a shadow in the white.", "choice_a": "Use a guide-rope (Dex DC 11)", "consequence_a": "Success: You don't lose your way in the mist. (+1 Progress)", "choice_b": "Chant a navigation mantra", "consequence_b": "Success: Your inner sense of direction holds. (+100 XP)", "convergence": "A 'Fog-Stalker'—a spindly, long-limbed shadow—darts past you in the mist."},
            {"turn": 2, "narrative": "The tower looms up ahead, a jagged finger of stone. The stairs are slick with 'Fog-Condensate', which is as slippery as ice.", "choice_a": "Climb with pitons (Str DC 12)", "consequence_a": "Success: You make steady upward progress. (+1 Progress)", "choice_b": "Dash up the stairs (Dex DC 14)", "consequence_b": "Success: You reach the first landing before the fog can slow you. (+1 Progress)", "convergence": "The door to the lantern room is locked from the inside."},
            {"turn": 3, "narrative": "You hear a scratching sound from behind the door. A weak voice is sobbing inside: 'The light... it wasn't enough...'", "choice_a": "Break down the door (Str DC 14)", "consequence_a": "Success: The hinges snap, and you burst in. (+1 Progress)", "choice_b": "Pick the lock (Dex DC 13)", "consequence_b": "Success: You enter quietly. (+100 XP)", "convergence": "The Lantern-Watcher is huddled in the corner, holding a shard of broken glass. The main lantern is shattered."},
            {"turn": 4, "narrative": "The lantern used a 'Sol-Crystal' which has now been drained of its light. The room is filled with a small, localized vortex of fog.", "choice_a": "Soothe the Watcher (Char DC 13)", "consequence_a": "Success: He tells you the fog 'drank' the light. (+1 Lore)", "choice_b": "Examine the lantern base (Int DC 13)", "consequence_b": "Success: You find the 'Mana-Filter' is clogged with soot. (+1 Progress)", "convergence": "The fog-vortex begins to solidify into a 'Cloud-Wraith'."},
            {"turn": 5, "narrative": "The Wraith is made of swirling vapors and two glowing, violet eyes. It's feeding on the remaining mana in the room.", "choice_a": "Banish it with a 'Burst of Light'", "consequence_a": "Success: The Wraith shrieks and dissolves. (+100 XP)", "choice_b": "Trap it in a containment jar (Dex DC 14)", "consequence_b": "Success: You have a miniature storm in a bottle. (+1 Loot)", "convergence": "The room is clear, but you need a new light source immediately."},
            {"turn": 6, "narrative": "A scout ship's horn sounds in the distance. They're heading straight for the 'Jagged-Ridge'. You have less than a minute.", "choice_a": "Use your own weapon as a conduit", "consequence_a": "Success: Your weapon glows with an intense, holy light. (+1 Progress)", "choice_b": "Apply 'Flare-Powder' to the wick (DEX DC 15)", "consequence_b": "Success: You create a blinding, temporary signal. (+1 Progress)", "convergence": "The light cuts through the fog, painting the white world in a harsh, neon blue."},
            {"turn": 7, "narrative": "The scout ship swerves just in time. You see its silhouette pass safely by the tower, its horn sounding a note of gratitude.", "choice_a": "Maintain the signal (Str DC 14)", "consequence_a": "Success: You keep the light steady until the fleet passes. (+1 Progress)", "choice_b": "Fix the Sol-Crystal (Int DC 14)", "consequence_b": "Success: You restore the permanent light. (+1 Progress)", "convergence": "The Scourge-fog begins to lift, retreating into the frozen wastes."},
            {"turn": 8, "narrative": "The Watcher is beginning to recover. He thanks you and offers you his 'Fog-Glass' lens.", "choice_a": "Accept the lens", "consequence_a": "Success: You gain a tool that can see through any mist. (+1 Gear)", "choice_b": "Refuse and tell him to be more careful", "consequence_b": "Success: He promises to double-check the filters. (+1 Rep)", "convergence": "The sun begins to peek through the remaining clouds, illuminating the tower in gold."},
            {"turn": 9, "narrative": "As you descend the tower, you find a 'Fog-Cutter'—a piece of the Cloud-Wraith that didn't dissolve. It's solid, cold, and hums with energy.", "choice_a": "Harvest the Fog-Cutter (Int DC 14)", "consequence_a": "Success: You gain a rare component for 'Anti-Fog' gear. (+1 Loot)", "choice_b": "Bury it in the snow", "consequence_b": "Success: You return the energy to the wastes. (+1 Luck)", "convergence": "The horizon is clear, and the settlement's scouts are safe."},
            {"turn": 10, "narrative": "You look back at the tower. It stands as a lonely sentinel against the dark. The horizon is clear.", "choice_a": "Return to the settlement", "consequence_a": "Success: You bring news of the fleet's arrival. (+10 Morale)", "choice_b": "Stay for one more watch", "consequence_b": "Success: You find a deep sense of peace. (+1 Luck)", "convergence": "Quest Complete."}
        ],
        "conclusion": "The Fog-Watcher's Lantern was a direct target of a Cloud-Wraith. The fleet is safe, and the beacon burns through the Scourge.",
        "loot_table": ["Fog-Glass Lens", "Fog-Cutter Shard", "Crate of Void-Vellum", "750 Gold"],
        "risk_matrix": {"failure_threshold": 4, "penalty": "Scout ship lost. -5 Local Resources and a week of mourning."}
    }
]

for i, q in enumerate(db):
    for uq in final_batch:
        if q['id'] == uq['id']:
            db[i] = uq

p.write_text(json.dumps(db, indent=4), encoding='utf-8')
print("SUCCESS: SQ-23 to SQ-25 and SQ-30 upgraded/fixed to 10-turn Lush Standard.")
